INSERT INTO tbl_cards (hp, name, info, attacke, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(120, 'Charizard', 'Flame Pokémon', 'Fire Spin', '100', 'Water', 'None', '3', 4, 1, 1, 3),
(60, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', 'None', '1', 58, 1, 4, 1),
(50, 'Bulbasaur', 'Seed Pokémon', 'Vine Whip', '20', 'Fire', 'Water', '1', 44, 1, 3, 1),
(70, 'Ivysaur', 'Seed Pokémon', 'Razor Leaf', '30', 'Fire', 'Water', '2', 30, 1, 3, 2),
(100, 'Venusaur', 'Seed Pokémon', 'Solarbeam', '60', 'Fire', 'Water', '3', 15, 1, 3, 3),
(40, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', 'None', '1', 46, 1, 1, 1),
(80, 'Charmeleon', 'Flame Pokémon', 'Flamethrower', '50', 'Water', 'None', '2', 24, 1, 1, 2),
(60, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '20', 'Electric', 'None', '1', 63, 1, 2, 1),
(80, 'Wartortle', 'Turtle Pokémon', 'Water Gun', '40', 'Electric', 'None', '1', 42, 1, 2, 2),
(100, 'Blastoise', 'Shellfish Pokémon', 'Hydro Pump', '60', 'Electric', 'None', '3', 2, 1, 2, 3),
(90, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', 'Fighting', '1', 10, 2, 3, 1),
(100, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '30', 'Fighting', 'Psychic', '4', 11, 2, 7, 1),
(80, 'Electabuzz', 'Electric Pokémon', 'Thunderpunch', '30+', 'Fighting', 'None', '2', 20, 1, 4, 1),
(70, 'Jigglypuff', 'Balloon Pokémon', 'Lullaby', '0', 'Fighting', 'Psychic', '1', 54, 1, 7, 1),
(60, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', 'Psychic', '1', 56, 1, 7, 1),
(100, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '30', 'Psychic', 'None', '1', 7, 3, 6, 1),
(90, 'Hitmonchan', 'Punching Pokémon', 'Special Punch', '40', 'Psychic', 'None', '2', 7, 1, 6, 1),
(80, 'Gengar', 'Shadow Pokémon', 'Nightmare', '30', 'Psychic', 'None', '1', 5, 3, 5, 3),
(70, 'Haunter', 'Gas Pokémon', 'Hypnosis', '0', 'Psychic', 'None', '1', 29, 1, 5, 2),
(50, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'None', '1', 33, 1, 5, 1);
