INSERT INTO tbl_cards (hp, name, info, attacke, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id)
VALUES
(70, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'Psychic', '1', 61, 1, 7, 1),
(90, 'Raticate', 'Mouse Pokémon', 'Super Fang', '40', 'Fighting', 'Psychic', '2', 40, 1, 7, 2),
(60, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '20', 'Electric', 'Fighting', '1', 57, 1, 7, 1),
(80, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Electric', 'Fighting', '1', 22, 1, 7, 2),
(120, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '30', 'Electric', 'Fighting', '2', 8, 1, 7, 3),
(50, 'Spearow', 'Tiny Bird Pokémon', 'Peck', '10', 'Electric', 'Fighting', '1', 69, 1, 7, 1),
(80, 'Fearow', 'Beak Pokémon', 'Agility', '20', 'Electric', 'Fighting', '1', 36, 2, 7, 2),
(60, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Electric', 'Fighting', '1', 48, 1, 7, 1),
(90, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '30+', 'Electric', 'Fighting', '2', 34, 2, 7, 2),
(100, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '20x', 'Fighting', 'Psychic', '3', 5, 2, 7, 1),
(60, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', 'Psychic', '1', 56, 1, 7, 1),
(90, 'Persian', 'Classy Cat Pokémon', 'Scratch', '20', 'Fighting', 'Psychic', '2', 36, 2, 7, 2),
(70, 'Eevee', 'Evolution Pokémon', 'Tackle', '20', 'Fighting', 'Psychic', '1', 55, 2, 7, 1),
(80, 'Flareon', 'Flame Pokémon', 'Flamethrower', '50', 'Water', 'None', '2', 3, 2, 1, 2),
(80, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Electric', 'None', '2', 12, 2, 2, 2),
(80, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', 'None', '2', 4, 2, 4, 2),
(100, 'Tauros', 'Wild Bull Pokémon', 'Stomp', '20+', 'Fighting', 'Psychic', '2', 21, 2, 7, 1),
(90, 'Chansey', 'Egg Pokémon', 'Scrunch', '0', 'Fighting', 'Psychic', '1', 3, 1, 7, 1),
(70, 'Clefairy', 'Fairy Pokémon', 'Sing', '0', 'Fighting', 'Psychic', '1', 5, 1, 7, 1),
(90, 'Clefable', 'Fairy Pokémon', 'Metronome', '0', 'Fighting', 'Psychic', '2', 1, 1, 7, 2),
(60, 'Jigglypuff', 'Balloon Pokémon', 'Lullaby', '0', 'Fighting', 'Psychic', '1', 54, 1, 7, 1),
(80, 'Wigglytuff', 'Balloon Pokémon', 'Do the Wave', '10x', 'Fighting', 'Psychic', '2', 32, 2, 7, 2),
(70, 'Farfetch’d', 'Wild Duck Pokémon', 'Leek Slap', '30', 'Electric', 'Fighting', '1', 7, 1, 7, 1),
(100, 'Ditto', 'Transform Pokémon', 'Transform', '0', 'Fighting', 'Psychic', '1', 18, 3, 7, 1),
(60, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'None', '1', 62, 1, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'None', '2', 9, 1, 4, 2),
(70, 'Voltorb', 'Ball Pokémon', 'Tackle', '10', 'Fighting', 'None', '1', 67, 1, 4, 1),
(90, 'Electrode', 'Ball Pokémon', 'Explosion', '80', 'Fighting', 'None', '2', 2, 1, 4, 2),
(100, 'Zapdos', 'Electric Pokémon', 'Thunderstorm', '40', 'Fighting', 'None', '3', 15, 1, 4, 1),
(120, 'Mewtwo', 'Genetic Pokémon', 'Psychic', '40+', 'Psychic', 'None', '3', 10, 1, 5, 1);
